### ISSUE TITLE
Missing bus services

### ISSUE THREAD

**Issue by kennethlimcp** [yi-jiayu/bus-eta-bot#14]
Seems like data all is not giving all the bus eta timings any more?

```
Kenneth Lim:
Opp Cycle & Carriage (20059)
AYE
| Svc | Next |  2nd |  3rd |
|-----|------|------|------|
| 154 |    4 |   14 |   22 |
| 198 |   15 |   24 |    ? |
| 201 |    5 |   18 |   25 |
Showing 3 out of 3 services for this bus stop.

Last updated at 14 Sep 18 20:49 SGT
```

Last time:

```
Kenneth Lim:
Opp Cycle & Carriage (20059)
AYE
| Svc | Next |  2nd |  3rd |
|-----|------|------|------|
| 154 |    0 |    3 |   15 |
| 197 |    6 |   10 |   19 |
| 198 |    0 |    2 |    6 |
| 201 |    3 |   14 |   27 |
| 97  |    0 |    8 |   17 |
Showing 5 out of 5 services for this bus stop.

Last updated at 07 Dec 17 07:01 SGT
```

**Comment by yi-jiayu** [comment]
Looks like the two missing services travel through the city, so it could be because of F1 this week:

> Dear DataMall subscribers,
> 
> Due to F1 2018 road closures, please be informed that ETA data for diverted bus services in Bus Arrival API will be unavailable during this period, i.e. no data available or no updated data.
> 
> Please click [here](https://www.mytransport.sg/content/mytransport/home/happening/details.formula_1_2018_singapore_airlines_singapore_grand_prix.html?Id=bf7ff4533e90d86cb49d881857c893ef) for the F1 2018 Bus Diversion information.
> 
> Start Date/Time:
> 
> 12 Sep 2018, 0000 hrs
> 
> End Date/Time:               
> 
> 18 Sep 2018, 0200 hrs
> 
> For your kind attention please. Thank you.
> 
> Regards,
> LTA DataMall Team

I'll monitor the situation as well and see if it goes back to normal after F1 is over. I do think there should be some way to notify users about DataMall events, will think about it.

Thanks for the report!

**Comment by yi-jiayu** [comment]
@kennethlimcp The missing bus services are back for me now, are you still affected by this issue?

**Comment by kennethlimcp** [comment]
All good now. Thanks!
